// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFeinROJ9hR_NFXM5GhVjkf-z3BwAv8Q',
    appId: '1:583142743408:web:c8c3bc880761781a8683b5',
    messagingSenderId: '583142743408',
    projectId: 'register-page-bf9cf',
    authDomain: 'register-page-bf9cf.firebaseapp.com',
    storageBucket: 'register-page-bf9cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZV1-6Cv4L9KVoIbiSg3WE4PsmEwhBgn4',
    appId: '1:583142743408:android:8fe7df9c16ecee3f8683b5',
    messagingSenderId: '583142743408',
    projectId: 'register-page-bf9cf',
    storageBucket: 'register-page-bf9cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpzAjIaS0K5m67wVPoT4zKgHfVpxnToY',
    appId: '1:583142743408:ios:1c021425d5ca1fdc8683b5',
    messagingSenderId: '583142743408',
    projectId: 'register-page-bf9cf',
    storageBucket: 'register-page-bf9cf.appspot.com',
    iosClientId: '583142743408-r795uudhl2js5p4p5dev4q7heavvhe1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpzAjIaS0K5m67wVPoT4zKgHfVpxnToY',
    appId: '1:583142743408:ios:67c22eccc55e80ee8683b5',
    messagingSenderId: '583142743408',
    projectId: 'register-page-bf9cf',
    storageBucket: 'register-page-bf9cf.appspot.com',
    iosClientId: '583142743408-nu0r5am0obigl6snb26pleb7b9tktsog.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginscreen.RunnerTests',
  );
}
